server:
  port: 8081
  servlet:
    context-path: /
    
spring:
  datasource:
    url: jdbc:mariadb://localhost:3307/test
    username: maria
    password: 1234
    driver-class-name: org.mariadb.jdbc.Driver
  
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp